name = "Cargo,Cars,Crates-Aero"
author = "JozCo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77bb71a6c2427e0fc0dd6af6eb559d58696ff9a4c785abceb550c983d143e44a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
