name = "Cargo,Cars,Crates-Aero"
author = "JozCo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5062b3126ce9445af8a0ff4ed6b2df51b1ff2b2dfbdfda339fa57a060be430e3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
